{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "geoip-api.serviceAccountName" . }}
  labels:
    {{- include "geoip-api.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ default .Release.Namespace .Values.namespaceOverride | quote }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
