apiVersion: v1
kind: Service
metadata:
  name: spilo-postgres-metrics
  namespace: services
  labels:
    application: spilo
spec:
  clusterIP: None
  selector:
    application: spilo
  ports:
    - name: exporter
      port: 9187
      targetPort: exporter
      protocol: TCP
    - name: patroni
      port: 8008
      targetPort: 8008
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spilo-postgres
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - services
  selector:
    matchLabels:
      application: spilo
  endpoints:
    - port: exporter
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      honorLabels: true
    - port: patroni
      path: /
      interval: 30s
      scrapeTimeout: 10s