apiVersion: v1
kind: Secret
metadata:
  name: postgres-user.postgres.credentials.postgresql.acid.zalan.do
  namespace: services
  labels:
    application: spilo
    cluster-name: postgres
    team: sretest
type: Opaque
data:
  password: T3JQMHNvb3k4c0ZFUTY=
  username: cG9zdGdyZXMtdXNlcg==