# .github/workflows/docker-cd.yml
name: Build & Deploy on Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/caas/geoip-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write SSH private key
        run: |
          echo "${{ secrets.SSH_KEY }}" > id_rsa.pem
          chmod 600 ./id_rsa.pem

      - name: Write Ansible Vault password file
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASS }}" > vault-pass.txt
          chmod 600 vault-pass.txt

      - name: Install Ansible
        run: pip install ansible

      - name: Run Ansible playbook
        run: |
          ansible-playbook playbooks/install-app.yml \
            -i inventory \
            --private-key id_rsa.pem \
            --vault-password-file vault-pass.txt \
            -e "image_tag=${{ needs.build-and-push.outputs.tag }}"